---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: centos
    driver_config:
      image: centos:centos6
      forward: 8080:8080

suites:
  - name: default
    run_list:
      - recipe[galaxy::default]
    attributes:
